modLoader="javafml"

loaderVersion="[43,)"
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Su5eD/GregTech-Experimental/issues" 

[[mods]]
modId="gtexperimental"
version="${file.jarVersion}"
displayName="GregTech Experimental"
displayURL="https://github.com/Su5eD/GregTech-Experimental"
logoFile="GTE_Logo.png"
credits="Mr. Brain, TheSirusKing and matix for Textures, GregoriousTechnecities for GregTech3"
authors="Su5eD"
description='''
This addon adds the awesome technology of GregTech-Intergalactical to your world!
Fusion reactors, lightning rods and many other technologies and convenient recipes are added by this addon...
'''

[[dependencies.gtexperimental]]
    modId="forge"
    mandatory=true
    versionRange="[43.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gtexperimental]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2, 1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gtexperimental]]
    modId="ic2"
    mandatory=false
    versionRange="[2.9.14,)"
    ordering="AFTER"
    side="BOTH"
